{"uid":"538c207ed4e7d98f","name":"Тест на получение сообщения. Негативный. Неверный messageId","fullName":"api_test.tests.test_get_message#test_get_message_negative_not_found","historyId":"bf367d947fc332f6ed88b07e072c3de6","time":{"start":1732980814153,"stop":1732980814261,"duration":108},"status":"failed","statusMessage":"Failed: Error: 401","statusTrace":"get_message_endpoint = <api_test.endpoints.get_message_endpoint.GetMessageEndpoint object at 0x7fd2522f3490>\nheaders = {'Authorization': 'Bot MTI4NjYwOTgxOTEzNzk5ODg4Mw.Gj2Mlk.YsVgU6PYv7xVW5bl7RYt9DLg2QeCU4OXToIiSw', 'Content-Type': 'application/json'}\n\n    @allure.title(\"Тест на получение сообщения. Негативный. Неверный messageId\")\n    def test_get_message_negative_not_found(get_message_endpoint, headers):\n        with allure.step(\"Отправка запроса\"):\n            get_message_endpoint.get_message_request(headers, 123)\n        with allure.step(\"Проверка статус кода\"):\n>           get_message_endpoint.check_status_code(404)\n\napi_test/tests/test_get_message.py:9: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <api_test.endpoints.get_message_endpoint.GetMessageEndpoint object at 0x7fd2522f3490>\ncode = 404\n\n    def check_status_code(self, code):\n        if self.response.status_code == code:\n            pass\n        else:\n>           pytest.fail(f'Error: {self.response.status_code}')\nE           Failed: Error: 401\n\napi_test/endpoints/base_endpoint.py:35: Failed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"get_message_endpoint","time":{"start":1732980814153,"stop":1732980814153,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"headers","time":{"start":1732980814153,"stop":1732980814153,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"failed","statusMessage":"Failed: Error: 401","statusTrace":"get_message_endpoint = <api_test.endpoints.get_message_endpoint.GetMessageEndpoint object at 0x7fd2522f3490>\nheaders = {'Authorization': 'Bot MTI4NjYwOTgxOTEzNzk5ODg4Mw.Gj2Mlk.YsVgU6PYv7xVW5bl7RYt9DLg2QeCU4OXToIiSw', 'Content-Type': 'application/json'}\n\n    @allure.title(\"Тест на получение сообщения. Негативный. Неверный messageId\")\n    def test_get_message_negative_not_found(get_message_endpoint, headers):\n        with allure.step(\"Отправка запроса\"):\n            get_message_endpoint.get_message_request(headers, 123)\n        with allure.step(\"Проверка статус кода\"):\n>           get_message_endpoint.check_status_code(404)\n\napi_test/tests/test_get_message.py:9: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <api_test.endpoints.get_message_endpoint.GetMessageEndpoint object at 0x7fd2522f3490>\ncode = 404\n\n    def check_status_code(self, code):\n        if self.response.status_code == code:\n            pass\n        else:\n>           pytest.fail(f'Error: {self.response.status_code}')\nE           Failed: Error: 401\n\napi_test/endpoints/base_endpoint.py:35: Failed","steps":[{"name":"Отправка запроса","time":{"start":1732980814153,"stop":1732980814260,"duration":107},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"Проверка статус кода","time":{"start":1732980814260,"stop":1732980814260,"duration":0},"status":"failed","statusMessage":"Failed: Error: 401\n","statusTrace":"  File \"/home/runner/work/diplom/diplom/api_test/tests/test_get_message.py\", line 9, in test_get_message_negative_not_found\n    get_message_endpoint.check_status_code(404)\n  File \"/home/runner/work/diplom/diplom/api_test/endpoints/base_endpoint.py\", line 35, in check_status_code\n    pytest.fail(f'Error: {self.response.status_code}')\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/_pytest/outcomes.py\", line 178, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":2,"attachmentsCount":0,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"api_test.tests"},{"name":"suite","value":"test_get_message"},{"name":"host","value":"fv-az1382-957"},{"name":"thread","value":"2093-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"api_test.tests.test_get_message"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":3,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"4a7ffaa84a5daa17","reportUrl":"https://prollla.github.io/diplom/2//#testresult/4a7ffaa84a5daa17","status":"failed","statusDetails":"Failed: Error: 401","time":{"start":1732980799863,"stop":1732980799962,"duration":99}},{"uid":"fc65b51015433863","reportUrl":"https://prollla.github.io/diplom/1//#testresult/fc65b51015433863","status":"failed","statusDetails":"Failed: Error: 401","time":{"start":1732980694899,"stop":1732980694991,"duration":92}}]},"tags":[]},"source":"538c207ed4e7d98f.json","parameterValues":[]}